name: Build and publish image to DockerHub

on:
  push:
    branches:
      - master
    paths:
      - "./Dockerfile"

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build . -t markfinerty/dockerized-express:latest
      - name: push image to DockerHub
        run: |
          docker login -u markfinerty -p ${{ secrets/DOCKER_HUB_TOKEN }}
          docker push markfinerty/dockerized-express:latest
